development:
  import_presentations:
    class: ImportPresentationsJob
    schedule: "0 9 * * *"
  update_presentations:
    class: PresentationAutoUpdateJob
    schedule: "0,10,20,30,40,50 10-17 * * *"

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  import_presentations:
    class: ImportPresentationsJob
    schedule: "0 9 * * *"
  update_presentations:
    class: PresentationAutoUpdateJob
    schedule: "0,10,20,30,40,50 10-17 * * *"
